name: Format

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install luacheck
        run: sudo apt-get install luarocks && sudo luarocks install luacheck
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
